version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/mydb?schema=public
    ports:
      - 1300:3000
    depends_on:
      - db
    command: >
      sh -c "
      pnpm dlx prisma generate &&
      pnpm dlx prisma db push &&
      pnpm start
      "

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    ports:
      - 5432
